server:
  port: 8761

spring:
  application:
    name: eureka-service

#Eureka Setting
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    enabled: true
    eureka-server-connect-timeout-seconds: 5
