server:
  port: 8761

spring:
  application:
    name: eureka-service

#Eureka Setting
eureka:
  instance:
    hostname: localhost #untuk dicoba di localhost
  client:
    register-with-eureka: false
    fetch-registry: false
